### ISSUE TITLE
The 503 error

### ISSUE THREAD

**Issue by bobo-wangyan** [OwO-Network/DeepLX#160] opened 2024-11-26 10:14 UTC
The 503 error appeared again. It was still possible to request yesterday. I am using the free mode. Has the API changed again?
{
    "code": 503,
    "message": "Translation failed"
}

**Comment by Gol2dragon** [comment] 2024-11-27 06:21
same problem as yours

**Comment by lurudong** [comment] 2024-11-28 12:50
same problem as yours

**Comment by MRchenao** [comment] 2024-11-29 02:19
same errors

**Comment by Rikj000** [comment] 2024-11-29 17:46
Duplicate of #149

**Closed** 2024-11-30 07:05 UTC

**Comment by missuo** [comment] 2024-11-30 07:18
Thank you for the contribution of @96368a. #161 

The issue has been fixed, please update to v0.9.9.
